# Generated by Django 4.0.3 on 2022-03-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10, unique=True)),
                ('module_title', models.CharField(max_length=200, unique=True)),
                ('student_reg_number', models.CharField(max_length=50, unique=True)),
                ('marks', models.IntegerField(max_length=5)),
                ('start_periode', models.DateTimeField()),
                ('end_periode', models.DateTimeField()),
                ('add', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
