# Generated by Django 4.0.3 on 2022-03-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('module_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('module_title', models.CharField(max_length=200)),
                ('module_credit', models.IntegerField()),
                ('module_description', models.TextField()),
                ('add', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_number', models.CharField(max_length=50, unique=True)),
                ('marks', models.IntegerField()),
                ('status', models.CharField(choices=[('Final', 'Final'), ('Provisory', 'Provisory'), ('Cancel', 'Cancel')], default='Provisory', max_length=50)),
                ('start_periode', models.DateTimeField()),
                ('end_periode', models.DateTimeField()),
                ('add', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
