# Generated by Django 4.0.3 on 2022-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='module_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='module_title',
            field=models.CharField(max_length=200),
        ),
    ]
