# Generated by Django 3.2.10 on 2022-06-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enroll_booklet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20)),
                ('student_reg_number', models.CharField(max_length=20)),
                ('due_period', models.DateTimeField()),
                ('marks', models.IntegerField(default=0)),
                ('booklet', models.IntegerField(default=0)),
            ],
        ),
    ]
