# Generated by Django 3.2.10 on 2022-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_capture_due_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='booklet',
            field=models.CharField(max_length=20),
        ),
    ]
